version: '3.9'

services:
  app:
    image: markoshust/magento-php:8.1-fpm
    container_name: magento_app
    volumes:
      - ./src:/var/www/html
      - ./src/app/code:/var/www/html/app/code
      - ./src/app/design:/var/www/html/app/design
      - ./src/app/etc:/var/www/html/app/etc
      - ./src/var:/var/www/html/var
      - ./src/pub/media:/var/www/html/pub/media
      - ./src/pub/static:/var/www/html/pub/static
      - ./src/generated:/var/www/html/generated
    ports:
      - '9000:9000'
    environment:
      PHP_MEMORY_LIMIT: 2G
      PHP_ENABLE_XDEBUG: 0
    depends_on:
      - db
      - elasticsearch

  web:
    image: markoshust/magento-nginx:1.22
    container_name: magento_web
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:10.4
    container_name: magento_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - db-data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: magento_elasticsearch
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms1g -Xmx1g'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'

  redis:
    image: redis:6.2
    container_name: magento_redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  db-data:
  es-data:
  redis-data:
